ValidOptions <- 
structure(list(`NULL` = structure(list(V1 = c("WSNSupport", "X", 
"X", "", "X", "X", ""), V2 = c("SCSSupport", "X", "", "X", "X", 
"", "X"), V3 = c("SCSPreferred", "X", "X", "X", "", "", ""), 
    V4 = c("Data Sources", "SCS", "WSN", "SCS", "WSN", "WSN", 
    "SCS")), .Names = c("V1", "V2", "V3", "V4"), row.names = c(NA, 
-7L), class = "data.frame"), `Data Provider Selection Criteria` = structure(list(
    WSNSupport = c("X", "X", "", "X", "X", ""), SCSSupport = c("X", 
    "", "X", "X", "", "X"), SCSPreferred = c("X", "X", "X", "", 
    "", ""), `Data Sources` = c("SCS", "WSN", "SCS", "WSN", "WSN", 
    "SCS")), .Names = c("WSNSupport", "SCSSupport", "SCSPreferred", 
"Data Sources"), row.names = c(NA, -6L), class = "data.frame"), 
    `NULL` = structure(list(appKeyrequired = c("targetsrequired", 
    "startDaterequired", "endDaterequired", "unitOfMeasureoptional", 
    "dataItemsoptional", "prioritizeSCSoptional"), `Registered users are issued their own unique application key. The application key is required for each
                                data request. Notice that authentication through a username and password is not required. The system simply
                                identifies you through the application key.` = c("targets are geographies or weather stations of interest. targets answers the \r\n                                question, \"What area or station am I reporting on? The targets parameter may specify one-to-many \r\n                                stations, zip codes, coordinates, or street addresses; however, you are not allowed to mix values from\r\n                                different categories. This means the targets parameter must contain only stations, only\r\n                                zip codes, only coordinates, or only street addresses. You will receive an error if you attempt to mix\r\n                                different category types. The following is the category list:\r\n                                A comma delimited list of WSN station numbers\r\n                                    A comma delimited list of California zip codes\r\n                                    A semicolon delimited list of decimal-degree coordinates\r\n                                    A semicolon delimited list of street addresses\r\n                                Examples:ex: \"2, 80, 127\" weather station list (comma delimited)ex: \"95823, 90017\" zip code list (comma delimited)ex: \"lat=34.99,lng=-118.34; lat=36.45,lng=-118.16\" (semicolon delimited)ex: \"addr-name=State Capitol,addr=1315 10th Street  Sacramento, CA 95814;addr-name=Grauman's Chinese Theatre,addr=6925 Hollywood Boulevard, Los Angeles, CA 90028\" (semicolon delimited)", 
    "Specifies the start date. The data format is \"yyyy-mm-dd\".\r\n                                Example:\r\n                                2012-01-01", 
    "Specifies the end date. The data format is \"yyyy-mm-dd\".\r\n                                Example:\r\n                                2012-01-01", 
    "The unitOfMeasure may be either 'E' for English units or 'M' for metric units. The value\r\n                                of this parameter will affect data values in the response. For example, designating \r\n                                English units will result in temperature values being returned in Fahrenheit rather than Celsius.\r\n                                Default:\r\n                                'E'", 
    "dataItems specifies one-to-many comma delimited data elements to include in your\r\n                                response. See the Data Items section for a complete list of possible \r\n                                data element values.Default:\r\n                                day-asce-eto, day-precip, day-sol-rad-avg, day-vap-pres-avg, day-air-tmp-max, day-air-tmp-min, day-air-tmp-avg, day-rel-hum-max, day-rel-hum-min, day-rel-hum-avg, day-dew-pnt, day-wind-spd-avg, day-wind-run, day-soil-tmp-avg", 
    "This parameter is relevant only when the targets parameter contains zip code(s). The value\r\n                                for this parameter may be either 'Y' or 'N'. See the Considerations for Zip Code Requests\r\n                                section above for details.\r\n\r\n                                Default:\r\n                                'Y'"
    )), .Names = c("appKeyrequired", "Registered users are issued their own unique application key. The application key is required for each\r\n                                data request. Notice that authentication through a username and password is not required. The system simply\r\n                                identifies you through the application key."
    ), row.names = c(NA, -6L), class = "data.frame"), `Daily Data Items` = structure(list(
        Name = c("Average Air Temperature", "Average Air Temperature", 
        "Minimum Air Temperature", "Dew Point", "CIMIS ETo", 
        "ASCE ETo", "ASCE ETr", "Precipitation", "Average Relative Humidity", 
        "Maximum Relative Humidity", "Minimum Relative Humidity", 
        "Average Soil Temperature", "Maximum Soil Temperature", 
        "Minimum Soil Temperature", "Average Solar Radiation", 
        "Net Solar Radiation", "Maximum Vapor Pressure", "Average Vapor Pressure", 
        "Wind East-North-East", "Wind East-South-East", "Wind North-North-East", 
        "Wind North-North-West", "Wind Run", "Average Wind Speed", 
        "Wind South-South-West", "Wind West-North-West", "Wind West-South-West"
        ), `Data Item` = c("day-air-tmp-avg", "day-air-tmp-avg", 
        "day-air-tmp-min", "day-dew-pnt", "day-eto", "day-asce-eto", 
        "day-asce-etr", "day-precip", "day-rel-hum-avg", "day-rel-hum-max", 
        "day-rel-hum-min", "day-soil-tmp-avg", "day-soil-tmp-max", 
        "day-soil-tmp-min", "day-sol-rad-avg", "day-sol-rad-net", 
        "day-vap-pres-max", "day-vap-pres-avg", "day-wind-ene", 
        "day-wind-ese", "day-wind-nne", "day-wind-nnw", "day-wind-run", 
        "day-wind-spd-avg", "day-wind-ssw", "day-wind-wnw", "day-wind-wsw"
        ), Class = c("Daily", "Daily", "Daily", "Daily", "Daily", 
        "Daily", "Daily", "Daily", "Daily", "Daily", "Daily", 
        "Daily", "Daily", "Daily", "Daily", "Daily", "Daily", 
        "Daily", "Daily", "Daily", "Daily", "Daily", "Daily", 
        "Daily", "Daily", "Daily", "Daily"), `Data Provider Support` = c("WSN", 
        "WSN", "WSN", "WSN", "WSN", "WSN & SCS", "WSN", "WSN", 
        "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", "WSN & SCS", 
        "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", 
        "WSN", "WSN", "WSN", "WSN")), .Names = c("Name", "Data Item", 
    "Class", "Data Provider Support"), row.names = c(NA, -27L
    ), class = "data.frame"), `Hourly Data Items` = structure(list(
        Name = c("Air Temperature", "Dew Point", "CIMIS ETo", 
        "Net Radiation", "ASCE ETo", "ASCE ETr", "Precipitation", 
        "Relative Humidity", "Resultant Wind", "Soil Temperature", 
        "Solar Radiation", "Vapor Pressure", "Wind Direction", 
        "Wind Speed"), `Data Item` = c("hly-air-tmp", "hly-dew-pnt", 
        "hly-eto", "hly-net-rad", "hly-asce-eto", "hly-asce-etr", 
        "hly-precip", "hly-rel-hum", "hly-res-wind", "hly-soil-tmp", 
        "hly-sol-rad", "hly-vap-pres", "hly-wind-dir", "hly-wind-spd"
        ), Class = c("Hourly", "Hourly", "Hourly", "Hourly", 
        "Hourly", "Hourly", "Hourly", "Hourly", "Hourly", "Hourly", 
        "Hourly", "Hourly", "Hourly", "Hourly"), `Data Provider Support` = c("WSN", 
        "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", "WSN", 
        "WSN", "WSN", "WSN", "WSN", "WSN")), .Names = c("Name", 
    "Data Item", "Class", "Data Provider Support"), row.names = c(NA, 
    -14L), class = "data.frame"), Exceptions = structure(list(
        Code = c("ERR1006", "ERR1019", "ERR1031", "ERR1034", 
        "ERR1035", "ERR1025", "ERR2006", "ERR2115", "ERR2114", 
        "ERR2007", "ERR1010", "ERR1011", "ERR1012", "ERR1032", 
        "ERR2112"), Name = c("INVALID APP KEY", "STATION NOT FOUND", 
        "UNSUPPORTED ZIP CODE", "COORD NOT IN CA", "DATA ITEM NOT FOUND", 
        "INVALID COORDINATE", "INVALID TARGET", "INVALID ADDRESS DATA ITEM", 
        "INVALID COORDINATE DATA ITEM", "HLY COORDINATES FAULT", 
        "FUTURE DATE FAULT", "ORIGIN DATE FAULT", "DATE ORDER FAULT", 
        "INVALID UNIT OF MEASURE", "DATA VOLUME VIOLATION"), 
        `HTTP Code` = c("403 - Forbidden", "404 - Not Found", 
        "404 - Not Found", "404 - Not Found", "404 - Not Found", 
        "400 - Bad Request", "400 - Bad Request", "400 - Bad Request", 
        "400 - Bad Request", "400 - Bad Request", "400 - Bad Request", 
        "400 - Bad Request", "400 - Bad Request", "400 - Bad Request", 
        "400 - Bad Request"), Description = c("The appKey parameter contains an invalid application key.", 
        "The targets parameter contains a value recognized as an invalid station number.", 
        "The targets parameter contains a value recognized as an unsupported zip code.", 
        "The targets parameter contains a value recognized as a coordinate outside the state of California.", 
        "The dataItems parameter contains an invalid data item.", 
        "The targets parameter contains a value recognized as an invalid coordinate.", 
        "The targets parameter that cannot be classified as a valid target type.", 
        "The targets parameter contains a data item this is not either 'day-asce-eto', 'day-sol-rad-avg'.", 
        "The targets parameter contains a data item this is not either 'day-asce-eto', 'day-sol-rad-avg'.", 
        "The targets parameter invalidly contains hourly data items for SCS data.", 
        "The startDate and/or endDate parameters specify future dates.", 
        "The startDate and/or endDate parameters specify dates before June 7st, 1982, which is the earliest date for CIMIS data.", 
        "The startDate is greater than the endDate.", "The unitOfMeasure parameter is something other than 'E' or 'M'.", 
        "The request exceeds data limitations.")), .Names = c("Code", 
    "Name", "HTTP Code", "Description"), row.names = c(NA, -15L
    ), class = "data.frame")), .Names = c("NULL", "Data Provider Selection Criteria", 
"NULL", "Daily Data Items", "Hourly Data Items", "Exceptions"
))
